services:
  - type: web
    name: nfs-ar-usdz
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y blender
      npm install
    startCommand: npm start
    envVars:
      - key: PUBLIC_BASE_URL
        value: https://RENDER_URL_PLACEHOLDER
